export type MuscleId =
  | "biceps"
  | "triceps"
  | "forearms"
  | "chest"
  | "front-delts"
  | "side-delts"
  | "rear-delts"
  | "lats"
  | "upper-back"
  | "lower-back"
  | "traps"
  | "abs"
  | "obliques"
  | "glutes"
  | "quads"
  | "hamstrings"
  | "calves";

export type BodyView = "front" | "back";
export type ExercisePopularity = "most-popular" | "common" | "less-common";
export type EquipmentId =
  | "bodyweight"
  | "dumbbells"
  | "barbell"
  | "weight_plates"
  | "bench"
  | "squat_rack"
  | "pull_up_bar"
  | "cable_machine"
  | "resistance_bands"
  | "kettlebells"
  | "cardio_equipment";

export type ExerciseVisual = {
  category: string;
  popularity: ExercisePopularity;
  equipment: EquipmentId[];
  primary: MuscleId[];
  secondary: MuscleId[];
  views: BodyView[];
  demoId?: string;
};

export const popularityChoices = [
  ["most-popular", "Most Popular"],
  ["common", "Common"],
  ["less-common", "Less Common"],
] as const satisfies readonly (readonly [ExercisePopularity, string])[];

export const equipmentChoices = [
  ["bodyweight", "Bodyweight"],
  ["dumbbells", "Dumbbells"],
  ["barbell", "Barbell"],
  ["weight_plates", "Weight plates"],
  ["bench", "Bench"],
  ["squat_rack", "Squat rack / cage"],
  ["pull_up_bar", "Pull-up bar"],
  ["cable_machine", "Cable machine"],
  ["resistance_bands", "Resistance bands"],
  ["kettlebells", "Kettlebells"],
  ["cardio_equipment", "Cardio equipment"],
] as const satisfies readonly (readonly [EquipmentId, string])[];

export const muscleLabels: Record<MuscleId, string> = {
  biceps: "Biceps",
  triceps: "Triceps",
  forearms: "Forearms",
  chest: "Chest",
  "front-delts": "Front delts",
  "side-delts": "Side delts",
  "rear-delts": "Rear delts",
  lats: "Lats",
  "upper-back": "Upper back",
  "lower-back": "Lower back",
  traps: "Traps",
  abs: "Abs",
  obliques: "Obliques",
  glutes: "Glutes",
  quads: "Quads",
  hamstrings: "Hamstrings",
  calves: "Calves",
};

const defineExercise = (
  category: string,
  popularity: ExercisePopularity,
  equipment: EquipmentId[],
  primary: MuscleId[],
  secondary: MuscleId[],
  views: BodyView[],
  demoId?: string,
): ExerciseVisual => ({
  category,
  popularity,
  equipment,
  primary,
  secondary,
  views,
  demoId,
});

const popular = "most-popular" as const;
const common = "common" as const;
const lessCommon = "less-common" as const;

// Each entry owns all of its display, filtering, anatomy, and asset metadata.
export const exerciseCatalog: Record<string, ExerciseVisual> = {
  "Barbell Curl": defineExercise(
    "Arms",
    popular,
    ["barbell"],
    ["biceps"],
    ["forearms"],
    ["front"],
    "Barbell_Curl",
  ),
  "Dumbbell Bicep Curl": defineExercise(
    "Arms",
    popular,
    ["dumbbells"],
    ["biceps"],
    ["forearms"],
    ["front"],
    "Dumbbell_Bicep_Curl",
  ),
  "Hammer Curl": defineExercise(
    "Arms",
    popular,
    ["dumbbells"],
    ["biceps", "forearms"],
    [],
    ["front"],
    "Hammer_Curls",
  ),
  "Preacher Curl": defineExercise(
    "Arms",
    popular,
    ["dumbbells", "bench"],
    ["biceps"],
    ["forearms"],
    ["front"],
    "Preacher_Curl",
  ),
  "Cable Tricep Pushdown": defineExercise(
    "Arms",
    popular,
    ["cable_machine"],
    ["triceps"],
    [],
    ["back"],
    "Triceps_Pushdown",
  ),
  "Skull Crusher": defineExercise(
    "Arms",
    popular,
    ["barbell", "bench"],
    ["triceps"],
    [],
    ["back"],
    "Lying_Triceps_Press",
  ),
  "Overhead Tricep Extension": defineExercise(
    "Arms",
    popular,
    ["dumbbells"],
    ["triceps"],
    [],
    ["back"],
    "Standing_Dumbbell_Triceps_Extension",
  ),
  "Tricep Dip": defineExercise(
    "Arms",
    popular,
    ["bodyweight", "bench"],
    ["triceps"],
    ["chest", "front-delts"],
    ["front", "back"],
    "Dips_-_Triceps_Version",
  ),
  "Concentration Curl": defineExercise(
    "Arms",
    common,
    ["dumbbells", "bench"],
    ["biceps"],
    ["forearms"],
    ["front"],
    "Concentration_Curls",
  ),
  "Incline Dumbbell Curl": defineExercise(
    "Arms",
    common,
    ["dumbbells", "bench"],
    ["biceps"],
    ["forearms"],
    ["front"],
    "Incline_Dumbbell_Curl",
  ),
  "Body Tricep Press": defineExercise(
    "Arms",
    lessCommon,
    ["bodyweight"],
    ["triceps"],
    ["chest", "front-delts"],
    ["front", "back"],
    "Body_Tricep_Press",
  ),
  "Close-Grip Push-Up": defineExercise(
    "Arms",
    common,
    ["bodyweight"],
    ["triceps"],
    ["chest", "front-delts"],
    ["front", "back"],
    "Push-Ups_-_Close_Triceps_Position",
  ),
  "Tricep Kickback": defineExercise(
    "Arms",
    common,
    ["dumbbells"],
    ["triceps"],
    [],
    ["back"],
    "Tricep_Dumbbell_Kickback",
  ),
  "Close-Grip Bench Press": defineExercise(
    "Arms",
    lessCommon,
    ["barbell", "bench", "squat_rack"],
    ["triceps"],
    ["chest", "front-delts"],
    ["front", "back"],
    "Close-Grip_Barbell_Bench_Press",
  ),

  "Barbell Bench Press": defineExercise(
    "Chest",
    popular,
    ["barbell", "bench", "squat_rack"],
    ["chest"],
    ["triceps", "front-delts"],
    ["front", "back"],
    "Barbell_Bench_Press_-_Medium_Grip",
  ),
  "Dumbbell Bench Press": defineExercise(
    "Chest",
    popular,
    ["dumbbells", "bench"],
    ["chest"],
    ["triceps", "front-delts"],
    ["front", "back"],
    "Dumbbell_Bench_Press",
  ),
  "Incline Dumbbell Press": defineExercise(
    "Chest",
    popular,
    ["dumbbells", "bench"],
    ["chest"],
    ["triceps", "front-delts"],
    ["front", "back"],
    "Incline_Dumbbell_Press",
  ),
  "Chest Fly": defineExercise(
    "Chest",
    popular,
    ["dumbbells", "bench"],
    ["chest"],
    ["front-delts"],
    ["front"],
    "Dumbbell_Flyes",
  ),
  "Cable Crossover": defineExercise(
    "Chest",
    popular,
    ["cable_machine"],
    ["chest"],
    ["front-delts"],
    ["front"],
    "Cable_Crossover",
  ),
  "Push-Up": defineExercise(
    "Chest",
    popular,
    ["bodyweight"],
    ["chest"],
    ["triceps", "front-delts", "abs"],
    ["front", "back"],
    "Pushups",
  ),
  "Incline Barbell Bench Press": defineExercise(
    "Chest",
    common,
    ["barbell", "bench", "squat_rack"],
    ["chest"],
    ["triceps", "front-delts"],
    ["front", "back"],
    "Barbell_Incline_Bench_Press_-_Medium_Grip",
  ),
  "Decline Push-Up": defineExercise(
    "Chest",
    common,
    ["bodyweight", "bench"],
    ["chest"],
    ["triceps", "front-delts"],
    ["front", "back"],
    "Decline_Push-Up",
  ),
  "Band Chest Fly": defineExercise(
    "Chest",
    lessCommon,
    ["resistance_bands"],
    ["chest"],
    ["front-delts"],
    ["front"],
    "Cross_Over_-_With_Bands",
  ),
  "Dumbbell Pullover": defineExercise(
    "Chest",
    lessCommon,
    ["dumbbells", "bench"],
    ["chest"],
    ["lats", "triceps"],
    ["front", "back"],
    "Straight-Arm_Dumbbell_Pullover",
  ),

  "Pull-Up": defineExercise(
    "Back",
    popular,
    ["bodyweight", "pull_up_bar"],
    ["lats"],
    ["biceps", "upper-back"],
    ["front", "back"],
    "Pullups",
  ),
  "Lat Pulldown": defineExercise(
    "Back",
    popular,
    ["cable_machine"],
    ["lats"],
    ["biceps", "upper-back"],
    ["front", "back"],
    "Wide-Grip_Lat_Pulldown",
  ),
  "Barbell Row": defineExercise(
    "Back",
    popular,
    ["barbell"],
    ["lats", "upper-back"],
    ["biceps", "lower-back"],
    ["front", "back"],
    "Bent_Over_Barbell_Row",
  ),
  "Dumbbell Row": defineExercise(
    "Back",
    popular,
    ["dumbbells", "bench"],
    ["lats"],
    ["biceps", "upper-back"],
    ["front", "back"],
    "One-Arm_Dumbbell_Row",
  ),
  "Seated Cable Row": defineExercise(
    "Back",
    popular,
    ["cable_machine"],
    ["lats", "upper-back"],
    ["biceps"],
    ["front", "back"],
    "Seated_Cable_Rows",
  ),
  "Face Pull": defineExercise(
    "Back",
    popular,
    ["cable_machine"],
    ["rear-delts", "upper-back"],
    ["biceps"],
    ["back"],
    "Face_Pull",
  ),
  "Back Extension": defineExercise(
    "Back",
    popular,
    ["bodyweight", "bench"],
    ["lower-back"],
    ["glutes", "hamstrings"],
    ["back"],
    "Hyperextensions_Back_Extensions",
  ),
  "Chin-Up": defineExercise(
    "Back",
    common,
    ["bodyweight", "pull_up_bar"],
    ["lats", "biceps"],
    ["upper-back"],
    ["front", "back"],
    "Chin-Up",
  ),
  "Inverted Row": defineExercise(
    "Back",
    common,
    ["bodyweight", "squat_rack"],
    ["upper-back", "lats"],
    ["biceps"],
    ["front", "back"],
    "Inverted_Row",
  ),
  "Straight-Arm Pulldown": defineExercise(
    "Back",
    lessCommon,
    ["cable_machine"],
    ["lats"],
    ["triceps"],
    ["front", "back"],
    "Straight-Arm_Pulldown",
  ),
  "Band Back Fly": defineExercise(
    "Back",
    common,
    ["resistance_bands"],
    ["upper-back", "rear-delts"],
    ["traps"],
    ["back"],
    "Back_Flyes_-_With_Bands",
  ),
  "Dumbbell Shrug": defineExercise(
    "Back",
    lessCommon,
    ["dumbbells"],
    ["traps"],
    ["forearms"],
    ["front", "back"],
    "Dumbbell_Shrug",
  ),

  "Overhead Press": defineExercise(
    "Shoulders",
    popular,
    ["barbell", "squat_rack"],
    ["front-delts", "side-delts"],
    ["triceps"],
    ["front", "back"],
    "Barbell_Shoulder_Press",
  ),
  "Dumbbell Shoulder Press": defineExercise(
    "Shoulders",
    popular,
    ["dumbbells"],
    ["front-delts", "side-delts"],
    ["triceps"],
    ["front", "back"],
    "Dumbbell_Shoulder_Press",
  ),
  "Lateral Raise": defineExercise(
    "Shoulders",
    popular,
    ["dumbbells"],
    ["side-delts"],
    ["traps"],
    ["front", "back"],
    "Side_Lateral_Raise",
  ),
  "Front Raise": defineExercise(
    "Shoulders",
    popular,
    ["dumbbells"],
    ["front-delts"],
    ["chest"],
    ["front"],
    "Front_Dumbbell_Raise",
  ),
  "Rear Delt Fly": defineExercise(
    "Shoulders",
    popular,
    ["dumbbells", "bench"],
    ["rear-delts"],
    ["upper-back"],
    ["back"],
    "Dumbbell_Lying_Rear_Lateral_Raise",
  ),
  "Upright Row": defineExercise(
    "Shoulders",
    popular,
    ["resistance_bands"],
    ["side-delts", "traps"],
    ["biceps"],
    ["front", "back"],
    "Upright_Row_-_With_Bands",
  ),
  "Arnold Press": defineExercise(
    "Shoulders",
    common,
    ["dumbbells"],
    ["front-delts", "side-delts"],
    ["triceps"],
    ["front", "back"],
    "Arnold_Dumbbell_Press",
  ),
  "Seated Cable Lateral Raise": defineExercise(
    "Shoulders",
    common,
    ["cable_machine"],
    ["side-delts"],
    ["traps"],
    ["front", "back"],
    "Cable_Seated_Lateral_Raise",
  ),
  "Handstand Push-Up": defineExercise(
    "Shoulders",
    common,
    ["bodyweight"],
    ["front-delts", "side-delts"],
    ["triceps"],
    ["front", "back"],
    "Handstand_Push-Ups",
  ),
  "Band Pull-Apart": defineExercise(
    "Shoulders",
    lessCommon,
    ["resistance_bands"],
    ["rear-delts", "upper-back"],
    ["traps"],
    ["back"],
    "Band_Pull_Apart",
  ),

  "Barbell Back Squat": defineExercise(
    "Legs",
    popular,
    ["barbell", "squat_rack"],
    ["quads", "glutes"],
    ["hamstrings", "lower-back"],
    ["front", "back"],
    "Barbell_Full_Squat",
  ),
  "Front Squat": defineExercise(
    "Legs",
    popular,
    ["barbell", "squat_rack"],
    ["quads", "glutes"],
    ["abs"],
    ["front", "back"],
    "Front_Squat_Clean_Grip",
  ),
  "Leg Press": defineExercise(
    "Legs",
    popular,
    ["cardio_equipment"],
    ["quads", "glutes"],
    ["hamstrings"],
    ["front", "back"],
    "Leg_Press",
  ),
  "Romanian Deadlift": defineExercise(
    "Legs",
    popular,
    ["barbell"],
    ["hamstrings", "glutes"],
    ["lower-back"],
    ["back"],
    "Romanian_Deadlift",
  ),
  "Leg Curl": defineExercise(
    "Legs",
    popular,
    ["cardio_equipment"],
    ["hamstrings"],
    ["calves"],
    ["back"],
    "Lying_Leg_Curls",
  ),
  "Leg Extension": defineExercise(
    "Legs",
    popular,
    ["cardio_equipment"],
    ["quads"],
    [],
    ["front"],
    "Leg_Extensions",
  ),
  "Walking Lunge": defineExercise(
    "Legs",
    popular,
    ["bodyweight"],
    ["quads", "glutes"],
    ["hamstrings", "calves"],
    ["front", "back"],
    "Bodyweight_Walking_Lunge",
  ),
  "Calf Raise": defineExercise(
    "Legs",
    popular,
    ["bodyweight"],
    ["calves"],
    [],
    ["front", "back"],
    "Standing_Calf_Raises",
  ),
  "Dumbbell Split Squat": defineExercise(
    "Legs",
    common,
    ["dumbbells"],
    ["quads", "glutes"],
    ["hamstrings"],
    ["front", "back"],
    "Split_Squat_with_Dumbbells",
  ),
  "Goblet Squat": defineExercise(
    "Legs",
    common,
    ["kettlebells"],
    ["quads", "glutes"],
    ["hamstrings", "abs"],
    ["front", "back"],
    "Goblet_Squat",
  ),
  "Barbell Hip Thrust": defineExercise(
    "Legs",
    common,
    ["barbell", "bench"],
    ["glutes"],
    ["hamstrings"],
    ["back"],
    "Barbell_Hip_Thrust",
  ),
  "Step-Up with Knee Raise": defineExercise(
    "Legs",
    common,
    ["bodyweight", "bench"],
    ["quads", "glutes"],
    ["hamstrings", "calves"],
    ["front", "back"],
    "Step-up_with_Knee_Raise",
  ),
  "Kettlebell Single-Leg Deadlift": defineExercise(
    "Legs",
    lessCommon,
    ["kettlebells"],
    ["hamstrings", "glutes"],
    ["lower-back"],
    ["back"],
    "Kettlebell_One-Legged_Deadlift",
  ),

  Plank: defineExercise(
    "Core",
    popular,
    ["bodyweight"],
    ["abs"],
    ["obliques", "front-delts"],
    ["front"],
    "Plank",
  ),
  Crunch: defineExercise(
    "Core",
    popular,
    ["bodyweight"],
    ["abs"],
    ["obliques"],
    ["front"],
    "Crunches",
  ),
  "Hanging Leg Raise": defineExercise(
    "Core",
    popular,
    ["bodyweight", "pull_up_bar"],
    ["abs"],
    ["quads"],
    ["front"],
    "Hanging_Leg_Raise",
  ),
  "Cable Crunch": defineExercise(
    "Core",
    popular,
    ["cable_machine"],
    ["abs"],
    ["obliques"],
    ["front"],
    "Cable_Crunch",
  ),
  "Russian Twist": defineExercise(
    "Core",
    popular,
    ["bodyweight"],
    ["obliques"],
    ["abs"],
    ["front"],
    "Russian_Twist",
  ),
  "Ab Wheel Rollout": defineExercise(
    "Core",
    popular,
    ["weight_plates"],
    ["abs"],
    ["front-delts", "lats"],
    ["front", "back"],
    "Ab_Roller",
  ),
  "Side Bridge": defineExercise(
    "Core",
    common,
    ["bodyweight"],
    ["obliques"],
    ["abs", "side-delts"],
    ["front"],
    "Side_Bridge",
  ),
  "Dead Bug": defineExercise(
    "Core",
    common,
    ["bodyweight"],
    ["abs"],
    ["obliques"],
    ["front"],
    "Dead_Bug",
  ),
  "Air Bike": defineExercise(
    "Core",
    common,
    ["bodyweight"],
    ["abs", "obliques"],
    [],
    ["front"],
    "Air_Bike",
  ),
  "Pallof Press": defineExercise(
    "Core",
    lessCommon,
    ["cable_machine"],
    ["obliques", "abs"],
    ["front-delts"],
    ["front"],
    "Pallof_Press",
  ),
  "Mountain Climber": defineExercise(
    "Core",
    common,
    ["bodyweight"],
    ["abs"],
    ["quads", "front-delts"],
    ["front"],
    "Mountain_Climbers",
  ),

  Deadlift: defineExercise(
    "Full Body & Conditioning",
    popular,
    ["barbell", "weight_plates"],
    ["glutes", "hamstrings"],
    ["lower-back", "quads", "traps"],
    ["front", "back"],
    "Barbell_Deadlift",
  ),
  "Kettlebell Swing": defineExercise(
    "Full Body & Conditioning",
    popular,
    ["kettlebells"],
    ["glutes", "hamstrings"],
    ["abs", "front-delts"],
    ["front", "back"],
    "One-Arm_Kettlebell_Swings",
  ),
  "Clean and Press": defineExercise(
    "Full Body & Conditioning",
    popular,
    ["barbell", "weight_plates"],
    ["quads", "front-delts"],
    ["glutes", "traps", "triceps"],
    ["front", "back"],
    "Clean_and_Press",
  ),
  Burpee: defineExercise(
    "Full Body & Conditioning",
    popular,
    ["bodyweight"],
    ["quads", "chest"],
    ["abs", "front-delts", "triceps"],
    ["front", "back"],
  ),
  "Farmer Carry": defineExercise(
    "Full Body & Conditioning",
    popular,
    ["dumbbells"],
    ["forearms", "traps"],
    ["abs", "quads"],
    ["front", "back"],
    "Farmers_Walk",
  ),
  "Sled Push": defineExercise(
    "Full Body & Conditioning",
    popular,
    ["cardio_equipment"],
    ["quads", "glutes"],
    ["chest", "front-delts", "calves"],
    ["front", "back"],
    "Sled_Push",
  ),
  "Kettlebell Turkish Get-Up": defineExercise(
    "Full Body & Conditioning",
    lessCommon,
    ["kettlebells"],
    ["glutes", "front-delts"],
    ["abs", "quads", "triceps"],
    ["front", "back"],
    "Kettlebell_Turkish_Get-Up_Squat_style",
  ),
  "Battle Ropes": defineExercise(
    "Full Body & Conditioning",
    lessCommon,
    ["cardio_equipment"],
    ["front-delts", "abs"],
    ["biceps", "triceps"],
    ["front", "back"],
    "Battling_Ropes",
  ),
  "Jump Rope": defineExercise(
    "Full Body & Conditioning",
    common,
    ["cardio_equipment"],
    ["calves"],
    ["quads", "front-delts"],
    ["front", "back"],
    "Rope_Jumping",
  ),
  "Kettlebell Thruster": defineExercise(
    "Full Body & Conditioning",
    common,
    ["kettlebells"],
    ["quads", "front-delts"],
    ["glutes", "triceps", "abs"],
    ["front", "back"],
    "Kettlebell_Thruster",
  ),
  "Bear Crawl Sled Drag": defineExercise(
    "Full Body & Conditioning",
    lessCommon,
    ["cardio_equipment"],
    ["abs", "front-delts"],
    ["quads", "triceps"],
    ["front", "back"],
    "Bear_Crawl_Sled_Drags",
  ),
};

export const exerciseGroups = Object.entries(exerciseCatalog).reduce<
  { label: string; exercises: string[] }[]
>((groups, [name, item]) => {
  const group = groups.find((candidate) => candidate.label === item.category);
  if (group) group.exercises.push(name);
  else groups.push({ label: item.category, exercises: [name] });
  return groups;
}, []);

export function getExerciseVisual(name: string) {
  return (exerciseCatalog as Record<string, ExerciseVisual>)[name];
}

export function demoFrames(demoId: string) {
  return {
    start: `/exercises/${demoId}/0.jpg`,
    finish: `/exercises/${demoId}/1.jpg`,
  };
}
